---
name: Lint (nix)
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Enable caching
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Install tools
        run: nix-env -iA nixfmt-rfc-style -f '<nixpkgs>'
      - name: Verify format
        run: nixfmt --check **/*.nix || { nixfmt --diff **/*.nix | sed 's/^/::error
          file=/' ; }
