---
name: Check
on: [pull_request]
jobs:
  checks:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Enable Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Checks  # uses hooks from pre-commit
        run: |
          set -o pipefail
          nix flake check --log-format raw 2>&1 |
            tee /tmp/nix-flake-check.log
      - name: Print full failure logs
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          DRV=$(grep "For full logs, run" /tmp/nix-flake-check.log | grep -oE "/nix/store/.*.drv")
          PR_NUMBER=$(cut -d"/" -f3 <<< "$GITHUB_REF")
          nix log "$DRV" |
            tee /tmp/nix-flake-check-full.log
          gh pr comment "$PR_NUMBER" --body /tmp/nix-flake-check-full.log
          exit 1
