on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  check_repo:
    uses: rbpatt2019/shared-workflows/.github/workflows/check_nix.yaml@main
    with:
      os: ubuntu-latest
