name: Update and Lint (nix)
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install tools (statix and nix-rfc-fmt)
        run: nix-env -i statix nix-rfc-fmt -f '<nixpkgs>'

      - name: Update flake
        run: nix flake update

      - name: Statix
        run: statix fix

      - name: Format
        run: nix fmt

      - name: Nix Flake Checker
        uses: DeterminateSystems/flake-checker-action@v9

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build(repo): lints and auto-updates"
